---
- hosts: slave
  tasks:
    
    - name: connect to database
      mysql_db:
        login_host: localhost
        login_user: root
        login_password: root
        name: keystone
        state: present
    - name: localhost keystone user
      mysql_user:
        login_host: localhost
        login_user: root
        login_password: root
        name: keystone
        password: keystone
        priv: keystone.*:ALL 
        state: present
    - name: database remote user
      mysql_user:
        host: '%' 
        login_user: root
        login_password: root
        name: keystone
        password: keystone
        priv: keystone.*:ALL 
        state: present




